// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using event_web_dev_project.Data;

#nullable disable

namespace event_web_dev_project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219185951_AddSoftDeleteToActivityPost")]
    partial class AddSoftDeleteToActivityPost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("event_web_dev_project.Models.ActivityPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationMode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CurrentMembers")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ActivityPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationMode = "Overflow allowed - Owner selects",
                            Category = "Sports",
                            CurrentMembers = 2,
                            Description = "We need 3 more players for a friendly football match this Sunday at Central Park. All skill levels welcome! We play 7v7 format.",
                            ExpiresAt = new DateTime(2026, 2, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Location = "Central Park, Field 3",
                            MaxMembers = 3,
                            PostedAt = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostedBy = "Alex Johnson",
                            Status = "Open",
                            Title = "Looking for Football Teammates - Sunday Match"
                        });
                });

            modelBuilder.Entity("event_web_dev_project.Models.PostApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("PostApplications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicantName = "Sarah Chen",
                            AppliedAt = new DateTime(2026, 2, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Message = "I'd love to join! I play midfielder and have experience.",
                            PostId = 1,
                            Status = "Accepted"
                        },
                        new
                        {
                            Id = 2,
                            ApplicantName = "Mike Rodriguez",
                            AppliedAt = new DateTime(2026, 2, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Count me in! I'm available on Sunday.",
                            PostId = 1,
                            Status = "Accepted"
                        },
                        new
                        {
                            Id = 3,
                            ApplicantName = "Emily Park",
                            AppliedAt = new DateTime(2026, 2, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "I'm interested! Can I bring a friend?",
                            PostId = 1,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 4,
                            ApplicantName = "Jessica Liu",
                            AppliedAt = new DateTime(2026, 2, 11, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Would love to join but I'm a beginner. Is that okay?",
                            PostId = 1,
                            Status = "Rejected"
                        });
                });

            modelBuilder.Entity("event_web_dev_project.Models.PostApplication", b =>
                {
                    b.HasOne("event_web_dev_project.Models.ActivityPost", "ActivityPost")
                        .WithMany("Applications")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityPost");
                });

            modelBuilder.Entity("event_web_dev_project.Models.ActivityPost", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
